//This script just contains the dictionary used by the translator

let dictionary = {
	'sex': 'seks',
    'sec': 'sex',
    'minecraft': 'minchiaft',
	'lmso': 'lmsi',
    'lmao': 'lmso',
	'lmmsaso': 'lmmsasosososososossoso',
	'lmfao': 'lmmsaso',
	'spanish girl': ['spanish girl', 'spanish girl', 'spanish girl', 'spanish girl', "uziel's exgf", 'spanish girl'],
    'spanish': ['spanoard', 'spaniard'],
	'girl': ['gurl', 'gril'],
	'about': 'avout',
	'moment': 'momento',
	'type': 'typ',
	' a ': ' an ',
	'a ': ['a ', 'an '],
	'text': 'tetx',
	'declare': 'adeclare',
	'this': ['thia', 'tgis'],
	'officially': 'oftficiallt',
	'me': 'em',
	'moemnt': 'momento',
	'from': 'fron',
	'form': 'from',
	'it': 'jt',
	'is': 'js',
	'because': 'becoasuse',
	'ct': 'cc',
	'ck': 'cc',
	'tought': 'thought',
	'the': ['tha', 'th3'],
	'supreme': 'supmeme',
	'about': 'avout',
	'friend': 'friedn',
	' ': [' ', ' ', ' ', ' ', ' ', 'n', ' ', ' ', ' ', ' ', ' ', ],
	'cc': ['cc', 'xx'],
	'bad': 'bed',
	'what': 'wot',
};
